//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class KBEngine_PacketReceiverWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(KBEngine.PacketReceiver), typeof(System.Object));
		L.RegFunction("networkInterface", networkInterface);
		L.RegFunction("process", process);
		L.RegFunction("startRecv", startRecv);
		L.RegFunction("New", _CreateKBEngine_PacketReceiver);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateKBEngine_PacketReceiver(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				KBEngine.NetworkInterface arg0 = (KBEngine.NetworkInterface)ToLua.CheckObject<KBEngine.NetworkInterface>(L, 1);
				KBEngine.PacketReceiver obj = new KBEngine.PacketReceiver(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: KBEngine.PacketReceiver.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int networkInterface(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			KBEngine.PacketReceiver obj = (KBEngine.PacketReceiver)ToLua.CheckObject<KBEngine.PacketReceiver>(L, 1);
			KBEngine.NetworkInterface o = obj.networkInterface();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int process(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			KBEngine.PacketReceiver obj = (KBEngine.PacketReceiver)ToLua.CheckObject<KBEngine.PacketReceiver>(L, 1);
			obj.process();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int startRecv(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			KBEngine.PacketReceiver obj = (KBEngine.PacketReceiver)ToLua.CheckObject<KBEngine.PacketReceiver>(L, 1);
			obj.startRecv();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

