//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class KBEngine_ProfileWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(KBEngine.Profile), typeof(System.Object));
		L.RegFunction("start", start);
		L.RegFunction("end", end);
		L.RegFunction("New", _CreateKBEngine_Profile);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateKBEngine_Profile(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				string arg0 = ToLua.CheckString(L, 1);
				KBEngine.Profile obj = new KBEngine.Profile(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: KBEngine.Profile.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int start(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			KBEngine.Profile obj = (KBEngine.Profile)ToLua.CheckObject<KBEngine.Profile>(L, 1);
			obj.start();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int end(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			KBEngine.Profile obj = (KBEngine.Profile)ToLua.CheckObject<KBEngine.Profile>(L, 1);
			obj.end();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

